[tools]
node = "latest"
python = "latest"
go = "1.20" # final version before telemetry
lua = "latest"
stylua = "latest"
opencode = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
# Mise defaults to UV .venv if it's present
python.uv_venv_auto = true
